# Package Overview
package_name: hotel_cancellation_model

# Data Files
training_data_file: hotel_bookings.csv
# test_data_file: hotel_bookings.csv

# Variables
# The variable we are attempting to predict (is_cancelled)
target: is_canceled

pipeline_name: regression_model
pipeline_save_file: regression_model_output_v

# set train/test split
test_size: 0.2

# to set the random seed
random_state: 13